spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/fastsns
    username: root
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update #create -> drop
    show-sql: true